CREATE TABLE `CC_AUTINX` (
  `AUT_CODE` varchar(20) NOT NULL COMMENT '권한코드',
  `AUT_NAME` varchar(50) NOT NULL COMMENT '권한명',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  `CRT_ID` varchar(20) NOT NULL COMMENT '생성자 ID',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '변경일자',
  `UDT_ID` varchar(20) NOT NULL COMMENT '변경자 ID',
  PRIMARY KEY (`AUT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='권한정보';

CREATE TABLE `CC_BOARD` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `BOARD_SEQ` int(10) unsigned NOT NULL COMMENT '게시판 SEQ',
  `TITLE` varchar(512) NOT NULL COMMENT '게시물 제목',
  `CONTENT` text COMMENT '본문',
  `VISIT` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '조회수',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일자',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  PRIMARY KEY (`SEQ`),
  KEY `FK_CC_BOARD_CC_BOARD_MGMT` (`BOARD_SEQ`),
  CONSTRAINT `FK_CC_BOARD_CC_BOARD_MGMT` FOREIGN KEY (`BOARD_SEQ`) REFERENCES `CC_BOARD_MGMT` (`SEQ`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=163 DEFAULT CHARSET=utf8 COMMENT='게시판 데이터 관리';

CREATE TABLE `CC_BOARD_ATTACH` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `DOCUMENT_SEQ` int(10) unsigned NOT NULL COMMENT '문서 일련번호',
  `BOARD_SEQ` int(10) unsigned NOT NULL COMMENT '게시판 SEQ',
  `ATTACH_PATH` varchar(512) NOT NULL COMMENT '첨부파일 경로',
  `ATTACH_SIZE` int(10) unsigned NOT NULL COMMENT '첨부파일 크기',
  `ORDER` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '순서',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `SAVE_FILE_NAME` varchar(100) DEFAULT NULL COMMENT '실제 저장되는 파일명',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '원래 파일명',
  PRIMARY KEY (`SEQ`),
  KEY `FK_CC_BOARD_ATTACH_CC_BOARD` (`DOCUMENT_SEQ`),
  CONSTRAINT `FK_CC_BOARD_ATTACH_CC_BOARD` FOREIGN KEY (`DOCUMENT_SEQ`) REFERENCES `CC_BOARD` (`SEQ`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8 COMMENT='게시판 첨부파일 관리';

CREATE TABLE `CC_BOARD_MGMT` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `TITLE` varchar(128) NOT NULL COMMENT '게시판명',
  `LIST_COUNT_DASHBOARD` tinyint(3) unsigned NOT NULL DEFAULT '6' COMMENT 'Dashboard에 표출되는 목록 개수',
  `LIST_COUNT_COMMON` int(10) unsigned NOT NULL DEFAULT '10' COMMENT '목록페이지에 표출되는 목록 개수',
  `ATTACH_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '파일첨부 여부',
  `SHOW_DASHBOARD_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT 'Dashboard 표출여부',
  `ORDER_NUM` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '표출순서',
  `WIDTH` varchar(3) NOT NULL DEFAULT '50' COMMENT 'Dashboard에 표시되는 화면 넓이 (50%, 100%)',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `AUTH_CODE` varchar(20) NOT NULL COMMENT '권한코드',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COMMENT='게시판 목록 관리';

CREATE TABLE `CC_CATALOG` (
  `SCHEMA` varchar(128) NOT NULL COMMENT '스키마명',
  `TABLE` varchar(128) NOT NULL COMMENT '테이블명',
  `TABLE_COMMENT` varchar(512) DEFAULT NULL COMMENT '테이블설명',
  `COLUMN` varchar(128) NOT NULL COMMENT '컬럼명',
  `COLUMN_COMMENT` varchar(512) DEFAULT NULL COMMENT '컬럼설명',
  `DATA_TYPE` varchar(128) NOT NULL COMMENT '데이터 타입',
  `DATA_TYPE_LENGTH` int(10) unsigned DEFAULT NULL COMMENT '데이터 길이',
  `ORDER` int(10) unsigned DEFAULT NULL COMMENT '컬럼순서',
  `IS_PK` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'PK여부',
  `IS_NULLABLE` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'NULL 여부',
  `COLUMN_DEFAULT` varchar(512) DEFAULT NULL COMMENT '컬럼 기본 값',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입력일자'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='테이블관리(ETL에서 입력)';

CREATE TABLE `CC_COMMON_CODE` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '공통코드 일련번호',
  `COMM_GRP_SEQ` int(10) unsigned NOT NULL COMMENT '공통코드그룹 일련번호',
  `COMM_CD_ID` varchar(100) DEFAULT NULL COMMENT '공통코드ID',
  `COMM_CD_NM` varchar(100) DEFAULT NULL COMMENT '공통코드명',
  `COMM_CD_EXT1` varchar(50) DEFAULT NULL COMMENT '공통코드 EXT1',
  `COMM_CD_EXT2` varchar(50) DEFAULT NULL COMMENT '공통코드 EXT2',
  `COMM_CD_EXT3` varchar(50) DEFAULT NULL COMMENT '공통코드 EXT3',
  `COMM_CD_DESC` varchar(4000) DEFAULT NULL COMMENT '공통코드 설명',
  `SORT` int(10) unsigned NOT NULL COMMENT '공통코드 순서',
  `USE_YN` char(1) NOT NULL COMMENT '공통코드 사용여부',
  `CRT_DT` datetime NOT NULL COMMENT '생성일자',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `UDT_DT` datetime NOT NULL COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `COMM_GRP_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=159 DEFAULT CHARSET=utf8 COMMENT='공통코드정보';

CREATE TABLE `CC_COMMON_CODE_GROUP` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '공통코드그룹 일련번호',
  `COMM_GRP_NM` varchar(100) DEFAULT NULL COMMENT '공통코드그룹명',
  `CRT_DT` datetime NOT NULL COMMENT '생성일자',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `UDT_DT` datetime NOT NULL COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `COMM_GRP_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8 COMMENT='공통코드그룹정보';

CREATE TABLE `CC_DASHBOARD` (
  `SEQ` int(11) NOT NULL,
  `SERVICE_STAT_SQL` text COMMENT '서비스 상태 메시지 생성 SQL',
  `RESEARCH_TARGET_STAT_SQL` text COMMENT '연구대상 통계 정보 생성 SQL',
  `TITLE_1` varchar(128) DEFAULT NULL COMMENT 'Dashboard 대제목',
  `TITLE_2` varchar(128) DEFAULT NULL COMMENT 'Dashboard 소제목',
  `SHOW_MY_RESEARCH` char(1) NOT NULL DEFAULT 'Y' COMMENT '나의 연구현황 표출여부',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `SUMMARY_WIDTH` int(10) unsigned NOT NULL COMMENT 'SUMMARY 길이',
  PRIMARY KEY (`SEQ`),
  UNIQUE KEY `SEQ` (`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DASHBOARD 일반 사항';

CREATE TABLE `CC_DASHBOARD_CHART` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `TITLE` varchar(128) NOT NULL COMMENT '차트 제목',
  `TYPE` varchar(50) NOT NULL COMMENT '차트 종류',
  `DATA_SQL` text COMMENT '데이터 생성 SQL',
  `WIDTH` varchar(3) NOT NULL DEFAULT '50' COMMENT '차트 넓이. 50%, 100%',
  `MIN_HEIGHT` varchar(3) DEFAULT NULL COMMENT '최소높이',
  `SHOW_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '표출여부',
  `ORDER_NUM` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '표출순서',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `DIM` varchar(100) DEFAULT NULL COMMENT '차트 DIM',
  `MEASURE` varchar(100) DEFAULT NULL COMMENT '차트 MEASURE',
  `COLS` text COMMENT '차트 SQL컬럼',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 COMMENT='DASHBOARD 차트 관리';

CREATE TABLE `CC_DEPINX` (
  `DEPT_CODE` varchar(20) NOT NULL COMMENT '부서코드',
  `DEPT_NAME` varchar(50) NOT NULL COMMENT '부서명',
  `DEPT_MAST` varchar(20) NOT NULL COMMENT '상위부서코드',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  PRIMARY KEY (`DEPT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부서 정보';

CREATE TABLE `CC_DISINX_LOV` (
  `LOV_CD` varchar(1) DEFAULT NULL,
  `PER_CODE` varchar(7) DEFAULT NULL,
  `SEQ` int(19) DEFAULT NULL,
  `LOV_NM` varchar(29) DEFAULT NULL,
  `PER_NAME` varchar(12) DEFAULT NULL,
  `DEPT_CODE` varchar(6) DEFAULT NULL,
  `CODE` varchar(9) DEFAULT NULL,
  `ENAM` varchar(500) DEFAULT NULL,
  `KNAM` varchar(500) DEFAULT NULL,
  `SHARE_REQ_YN` varchar(1) DEFAULT NULL,
  `SHARE_REQ_DT` timestamp NULL DEFAULT NULL,
  `LDNG_DT` timestamp NULL DEFAULT NULL,
  `INSTCD` char(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CC_ETLLOG_ACCESS` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `JOB_ID` varchar(50) DEFAULT NULL COMMENT 'job id',
  `START_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '시작시간',
  `END_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '종료시간',
  `EXTRACT_COUNT` varchar(10) DEFAULT NULL COMMENT '추출건수',
  `LOAD_COUNT` varchar(10) DEFAULT NULL COMMENT '적재건수',
  `STATE` varchar(50) DEFAULT NULL COMMENT '상태',
  `STATE_MSG` varchar(200) DEFAULT NULL COMMENT '상태메세지',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='웹접속로그';

CREATE TABLE `CC_ITEM_CATE` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '항목분류(대) 일련번호',
  `CATE_NM` varchar(128) NOT NULL COMMENT '항목분류(대) 이름',
  `ORDER` int(10) unsigned NOT NULL COMMENT '출력순서',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8 COMMENT='연구항목분류(대)관리';

CREATE TABLE `CC_ITEM_CATE_DETL` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '항목분류(중) 일련번호',
  `ITEM_CATE_SEQ` int(10) unsigned NOT NULL COMMENT '항목분류(대) 일련번호',
  `CATE_NM` varchar(128) NOT NULL COMMENT '항목분류(중) 이름',
  `ORDER` int(10) unsigned NOT NULL DEFAULT '1',
  `SCHEMA` varchar(128) NOT NULL COMMENT '스키마명',
  `TABLE` varchar(128) NOT NULL COMMENT '테이블명',
  `TABLE_COMMENT` varchar(512) DEFAULT NULL COMMENT '테이블설명',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `BASE_DT_COLUMN` varchar(128) DEFAULT NULL COMMENT '테이블 기준일 컬럼명',
  `INSTCD_YN` char(1) DEFAULT NULL COMMENT '사업장적용여부',
  PRIMARY KEY (`SEQ`),
  KEY `CC_ITEM_CATE_DETL_CC_ITEM_CATE_FK` (`ITEM_CATE_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=1003 DEFAULT CHARSET=utf8 COMMENT='연구항목분류(중)관리';

CREATE TABLE `CC_ITEM_CONT` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `SHARE_CD` char(1) NOT NULL DEFAULT 'A' COMMENT '공유조건(P:개인, A:전체, D:과)',
  `CONDT_NM` varchar(512) NOT NULL COMMENT '연구조건명',
  `PER_CODE` varchar(20) NOT NULL COMMENT '사용자ID',
  `METH_CD` char(2) NOT NULL DEFAULT 'CS' COMMENT '연구종류(CS:단면, CC:사레대조, CH:코호트)',
  `CC_POP_NUM` int(10) unsigned DEFAULT NULL COMMENT '(사례대조) 모집단 숫자',
  `CC_CASE_NUM` int(10) unsigned DEFAULT NULL COMMENT '(사례대조) 사례군 숫자',
  `CC_SAM_NUM` int(10) unsigned DEFAULT NULL COMMENT '(사례대조) 대조군 배수',
  `CC_CONT_CD` char(1) DEFAULT NULL COMMENT '(사례대조) 대조군 배수',
  `CC_MAT_CD` varchar(3) DEFAULT NULL COMMENT '(사례대조) 대조군 매칭, ''AM'' : Age Match, ''SM'' : Sex Match, ''ASM'' : Age Sex Match',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `SAVE_CD` char(2) DEFAULT NULL COMMENT 'SC : 환자조회, SI : 연구조회',
  `DEPT_CODE` varchar(20) DEFAULT NULL,
  `CC_AGE_NUM` int(10) unsigned DEFAULT NULL COMMENT '(사례대조) 대조군 매칭 Age 범위',
  `INSTCD` varchar(3) DEFAULT NULL COMMENT '사업장코드',
  PRIMARY KEY (`SEQ`),
  KEY `CC_ITEM_CONT_CC_PERINX_FK` (`PER_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=577 DEFAULT CHARSET=utf8 COMMENT='사용자연구조건저장';

CREATE TABLE `CC_ITEM_CONT_DATA` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '데이터일련번호',
  `PER_CODE` varchar(200) NOT NULL COMMENT '사용자ID',
  `CONT_SEQ` int(10) unsigned NOT NULL COMMENT '사용자 연구조건 저장 일련번호',
  `DATA_NM` varchar(512) NOT NULL COMMENT '데이터명',
  `UDT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  `DATA_SEQ` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '사용자 연구조건에 대한 데이터 일련번호. 프로그램에서 따야 함.',
  `CRT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '변경일자',
  `TABLE_ID` varchar(100) DEFAULT NULL,
  `TABLE_CNT` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '데이터의 갯수',
  `TABLE_SIZE` decimal(10,2) DEFAULT NULL COMMENT '사용자테이블크기',
  PRIMARY KEY (`SEQ`),
  KEY `CC_ITEM_CONT_DATA_CC_PERINX_FK` (`PER_CODE`),
  KEY `CC_ITEM_CONT_DATA_CC_ITEM_CONT_FK` (`CONT_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=229 DEFAULT CHARSET=utf8 COMMENT='연구데이터저장관리';

CREATE TABLE `CC_ITEM_CONT_DATA_DETL` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '데이터상세일련번호',
  `DATA_SEQ` int(10) unsigned NOT NULL COMMENT '데이터 저장 일련번호',
  `COLUMN_ID` varchar(512) NOT NULL COMMENT '컬럼ID',
  `COLUMN_COMMENT` varchar(512) NOT NULL COMMENT '컬럼명',
  `UDT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  `CRT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '변경일자',
  `OLAP_YN` char(1) DEFAULT 'Y',
  `ITEM_SEQ` int(10) unsigned DEFAULT NULL,
  `DATA_TYPE` varchar(128) DEFAULT NULL,
  `ITEM_TYPE` char(3) DEFAULT NULL,
  `ADD_ITEM_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '추가아이템 여부 Y:추가',
  `HIDDEN_YN` varchar(100) DEFAULT NULL COMMENT '코호트연구 Agg 전체 HIDDEN여부',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=2934 DEFAULT CHARSET=utf8 COMMENT='연구데이터상세관리';

CREATE TABLE `CC_ITEM_CONT_DETL` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `ITEM_SEQ` int(10) unsigned NOT NULL COMMENT '연구항목 일련번호',
  `CONT_SEQ` int(10) unsigned NOT NULL COMMENT '연구조건 일련번호',
  `PER_CODE` varchar(20) NOT NULL COMMENT '사용자ID',
  `ORDER` int(10) unsigned NOT NULL COMMENT '정렬순서',
  `INC_EXC` char(3) NOT NULL DEFAULT 'INC' COMMENT '조건의 포함/제외 여부. ''INC'': 포함, ''EXC'': 제외',
  `TAB_CD` varchar(2) NOT NULL COMMENT '"화면테이블구분\n공통 ==> C:환자선택, [RC,R]:연구항목, I:개인데이터\n단면 == > P : 반복데이터관리\n코호트 ==> RE : 사건정의, RQ : 중도절단\n사례대조 ==> CP: 모집단, CA : 사례군, CO : 대조군"',
  `GR_LV` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '그룹레벨. 0: 그룹없음. 1~N : 그룹번호',
  `INPUT_VAL0` varchar(4000) DEFAULT NULL COMMENT '입력값 종류 : year, like, <, >, day, between, NULL',
  `INPUT_VAL1` varchar(1024) DEFAULT NULL COMMENT '입력값, 시작값',
  `INPUT_VAL2` varchar(1024) DEFAULT NULL COMMENT '입력 종료값',
  `CNT` int(10) unsigned DEFAULT NULL COMMENT '조회된 환자수',
  `AGG` varchar(5) DEFAULT NULL COMMENT '코호트 연구항목 기준 : first, last, 주기, 전체, 이전',
  `AND_OR` varchar(10) DEFAULT NULL COMMENT '조회 조건 : AND, OR, 주기번호(1주기, 2주기…)',
  `FIRST_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '기준일 최초 여부',
  `BASE_DT_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '기준일 여부',
  `RANGE_CD` char(1) DEFAULT NULL COMMENT '코호트 주기, 단면/사례대조 연구항목기준 범위',
  `RANGE_DN` int(10) unsigned DEFAULT NULL COMMENT '코호트 편차, 단면/사례대조 연구항목기준 편차',
  `DELETE_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `ITEM_TEXT` varchar(200) DEFAULT NULL COMMENT '항목텍스트',
  `IS_NULL_OR_BLANK` char(1) DEFAULT NULL COMMENT 'NULL_OR_BLANK여부',
  PRIMARY KEY (`SEQ`),
  KEY `CC_ITEM_CONT_DETL_CC_ITEM_MGMT_FK` (`ITEM_SEQ`),
  KEY `CC_ITEM_CONT_DETL_CC_ITEM_CONT_FK` (`CONT_SEQ`),
  KEY `CC_ITEM_CONT_DETL_CC_PERINX_FK` (`PER_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=8034 DEFAULT CHARSET=utf8 COMMENT='사용자연구조건상세관리';

CREATE TABLE `CC_ITEM_JOIN` (
  `SCHEMA_1` varchar(128) NOT NULL COMMENT '스키마명',
  `TABLE_1` varchar(128) NOT NULL COMMENT '테이블명',
  `COLUMN_1` varchar(128) NOT NULL COMMENT '컬럼명',
  `SCHEMA_2` varchar(128) NOT NULL COMMENT '조인 스키마명',
  `TABLE_2` varchar(128) NOT NULL COMMENT '조인 테이블명',
  `COLUMN_2` varchar(128) NOT NULL COMMENT '조인 컬럼명',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '변경일자'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='연구항목 조인 관리 테이블';

CREATE TABLE `CC_ITEM_JOIN_TEMP` (
  `SCHEMA_1` varchar(128) NOT NULL COMMENT '스키마명',
  `TABLE_1` varchar(128) NOT NULL COMMENT '테이블명',
  `COLUMN_1` varchar(128) NOT NULL COMMENT '컬럼명',
  `SCHEMA_2` varchar(128) NOT NULL COMMENT '조인 스키마명',
  `TABLE_2` varchar(128) NOT NULL COMMENT '조인 테이블명',
  `COLUMN_2` varchar(128) NOT NULL COMMENT '조인 컬럼명',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '변경일자'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='연구항목 조인 관리 테이블';

CREATE TABLE `CC_ITEM_MGMT` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '연구항목 일련번호',
  `SCHEMA` varchar(128) NOT NULL COMMENT '스키마명',
  `TABLE` varchar(128) NOT NULL COMMENT '테이블명',
  `TABLE_COMMENT` varchar(512) DEFAULT NULL COMMENT '테이블설명',
  `COLUMN` varchar(128) NOT NULL COMMENT '컬럼명',
  `COLUMN_COMMENT` varchar(512) DEFAULT NULL COMMENT '컬럼설명',
  `DATA_TYPE` varchar(128) DEFAULT NULL COMMENT 'Data Type',
  `ITEM_NM` varchar(128) NOT NULL COMMENT '항목명',
  `ORDER` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '출력순서',
  `SEARCH_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '검색여부 ==> ''Y'', ''N''',
  `ITEM_TYPE` char(3) NOT NULL DEFAULT 'TEX' COMMENT '항목종류 ==> DAT, COD, NUM, TEX',
  `CODE_TYPE` char(3) DEFAULT NULL COMMENT '항목이 코드일 경우 COD 종류. ''JSN'' : JSON, ''SQL'' : SQL',
  `CODE_SET` text COMMENT '"항목이 코드일 경우 코드 목록이 JSON값으로 정의됨. [{""M"":""남성"",""F"":""여성""}]\n항목을 선택하는 SQL문이 정의될수도 있음"',
  `POPUP_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '항목선택 팝업창 여부 (''Y'', ''N'')',
  `POPUP_PROGRAM_ID` varchar(128) DEFAULT NULL COMMENT 'POPUP=''Y''일 경우 팝업창 프로그램ID',
  `UPPER_TABLE` varchar(128) DEFAULT NULL COMMENT '상위테이블',
  `UPPER_COLUMN` varchar(128) DEFAULT NULL COMMENT '상위컬럼',
  `GMEC_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '중요여부',
  `HCC_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '다빈도 여부',
  `SYNONYM_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '동의어 적용 여부(TA에서 사용)',
  `ITEM_DESC` varchar(512) DEFAULT NULL COMMENT '항목설명',
  `CS_REPEAT_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '단면연구 반복데이터 조건 여부',
  `CH_DEFAULT_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '코호트연구 기본 연구항목 여부',
  `CH_CENSORING_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '코호트연구 중도절단 연구항목 여부',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `ITEM_CATE_SEQ` int(10) unsigned DEFAULT NULL,
  `ITEM_CATE_DETL_SEQ` int(10) unsigned DEFAULT NULL,
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `ITEM_CATE` varchar(100) DEFAULT NULL,
  `ITEM_CATE_DETL` varchar(100) DEFAULT NULL,
  `BASE_DT_COLUMN` varchar(128) DEFAULT NULL COMMENT '기준일 컬럼명',
  `POPUP_COLUMN` varchar(128) DEFAULT NULL COMMENT '팝업호출시 WHERE조건으로 사용하기 위한 컬럼',
  `ITEM_FIRST_YN` char(1) NOT NULL DEFAULT 'N',
  `INSTCD_YN` char(1) DEFAULT 'N' COMMENT '사업장코드여부',
  `SEARCH_CNT` bigint(20) unsigned DEFAULT '0' COMMENT '조회수카운트',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=3963 DEFAULT CHARSET=utf8 COMMENT='연구항목 관리';

CREATE TABLE `CC_LOG_ACCESS` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `TYPE` char(1) NOT NULL DEFAULT 'P' COMMENT '로그종류. ''L'':로그인, ''P'':페이지뷰',
  `REQUEST_URL` varchar(1024) NOT NULL COMMENT '요청페이지 URL',
  `PER_CODE` varchar(20) NOT NULL COMMENT '사용자ID',
  `ACCESS_IP` varchar(50) NOT NULL COMMENT '접속 CLIENT IP',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `MESSAGE` text COMMENT '에러,쿼리메시지',
  PRIMARY KEY (`SEQ`),
  KEY `CC_LOG_ACCESS_CC_PERINX_FK` (`PER_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=332773 DEFAULT CHARSET=utf8 COMMENT='웹접속로그';

CREATE TABLE `CC_LOTINX` (
  `LOCT_CODE` varchar(20) NOT NULL COMMENT '직급코드',
  `LOCT_NAME` varchar(100) NOT NULL COMMENT '직급명',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  PRIMARY KEY (`LOCT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='직급 관리';

CREATE TABLE `CC_MENU` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '메뉴 일련번호',
  `UPPER_SEQ` int(10) unsigned DEFAULT NULL COMMENT '상위메뉴 일련번호',
  `MENU_GBN_CD` char(8) DEFAULT NULL COMMENT '메뉴구분',
  `MENU_NM` varchar(100) DEFAULT NULL COMMENT '메뉴명',
  `MENU_URL` varchar(100) DEFAULT NULL COMMENT '메뉴URL',
  `SORT` int(10) unsigned NOT NULL COMMENT '메뉴 순서',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `CRT_DT` datetime NOT NULL COMMENT '생성일자',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `UDT_DT` datetime NOT NULL COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='메뉴정보';

CREATE TABLE `CC_MENU_AUTH` (
  `MENU_SEQ` int(10) unsigned NOT NULL COMMENT '메뉴SEQ',
  `AUT_CODE` varchar(20) NOT NULL COMMENT '권한코드',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  PRIMARY KEY (`MENU_SEQ`,`AUT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='메뉴권한정보';

CREATE TABLE `CC_OLAP_MGMT` (
  `OLAP_ID` varchar(10) DEFAULT NULL,
  `OLAP_URL` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CC_PERINX` (
  `PER_CODE` varchar(20) NOT NULL COMMENT '사용자ID',
  `PER_PASS` varchar(512) NOT NULL COMMENT '비밀번호',
  `PER_NAME` varchar(50) NOT NULL COMMENT '이름',
  `DEPT_CODE` varchar(20) NOT NULL COMMENT '부서코드',
  `LOCT_CODE` varchar(20) NOT NULL COMMENT '직급코드',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `FIRST_FLAG` char(1) NOT NULL DEFAULT 'N' COMMENT '초기접속여부 N:초기접속, Y:2회이상접속',
  `INSTCD` varchar(3) DEFAULT 'N' COMMENT '병원구분코드',
  KEY `CC_PERINX_CC_DEPINX_FK` (`DEPT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 정보';

CREATE TABLE `CC_PER_AUTH` (
  `PER_CODE` varchar(20) NOT NULL COMMENT '사용자ID',
  `AUT_CODE` varchar(20) NOT NULL COMMENT '권한코드',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  `INSTCD` varchar(3) DEFAULT 'N',
  PRIMARY KEY (`PER_CODE`,`AUT_CODE`),
  KEY `CC_PER_AUTH_CC_AUTINX_FK` (`AUT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 권한 매핑 정보';

CREATE TABLE `CC_REPORT_CATE` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호(분류코드)',
  `NAME` varchar(128) NOT NULL COMMENT '분류명',
  `ICON_PATH` varchar(128) NOT NULL COMMENT '정형보고서 분류 아이콘 경로',
  `SHOW_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '표출여부',
  `ORDER` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '표출순서',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8 COMMENT='정형보고서 분류 관리';

CREATE TABLE `CC_REPORT_PAGE` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `CATE_CODE` int(10) unsigned NOT NULL COMMENT '분류코드',
  `TITLE` varchar(128) NOT NULL COMMENT '보고서 이름',
  `URL` varchar(1024) NOT NULL COMMENT '보고서 URL',
  `USER_ID` varchar(20) DEFAULT NULL COMMENT 'TABLEAU USER_ID',
  `TARGET_ID` varchar(20) DEFAULT NULL COMMENT 'TABLEAU TARGET_ID',
  `AUT_CODE` varchar(20) DEFAULT NULL COMMENT '보고서 조회 권한 코드',
  `SHOW_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '표출여부',
  `ORDER` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '표출순서',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=16456 DEFAULT CHARSET=utf8 COMMENT='정형보고서 페이지 관리';

CREATE TABLE `CC_RSCH_APRV_MGMT` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'IRB 승인요청 일련번호',
  `PER_CODE` varchar(20) NOT NULL COMMENT '요청자 ID',
  `CONT_SEQ` int(10) unsigned NOT NULL COMMENT '연구조건 일련번호',
  `DATA_SEQ` int(10) unsigned NOT NULL COMMENT '데이터 일련번호',
  `RSCH_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '승인요청일자',
  `APRV_PER_CODE` varchar(20) DEFAULT NULL COMMENT '승인자 ID',
  `APRV_YN` char(1) DEFAULT NULL COMMENT '승인여부',
  `REJT_REASON` varchar(512) DEFAULT NULL COMMENT '거부사유',
  `PURPOSE_CD` varchar(3) DEFAULT NULL COMMENT '추출목적',
  `APRV_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '승인일자',
  PRIMARY KEY (`SEQ`),
  KEY `CC_RSCH_APRV_MGMT_CC_PERINX_FK` (`PER_CODE`),
  KEY `CC_RSCH_APRV_MGMT_CC_ITEM_CONT_FK` (`CONT_SEQ`),
  KEY `CC_RSCH_APRV_MGMT_CC_ITEM_CONT_DATA_FK` (`DATA_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8 COMMENT='IRB 승인 요청 관리';

CREATE TABLE `CC_SYNONYM` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '용어ID',
  `REP_SEQ` int(10) unsigned NOT NULL COMMENT '대표어 ID',
  `TERM` varchar(128) NOT NULL COMMENT '용어',
  `LANG` char(2) NOT NULL DEFAULT 'EN' COMMENT '언어코드. KO:한국어, EN:영어',
  `REP_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '대표어 여부',
  `DELETE_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8 COMMENT='동의어 사전 관리';

CREATE TABLE `CC_SYNONYM_ITEM_MAP` (
  `SEQ` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '연구항목-동의어관계 일련번호',
  `ITEM_CATE_SEQ` int(10) unsigned NOT NULL COMMENT '대분류 순번',
  `ITEM_CATE_DETL_SEQ` int(10) unsigned NOT NULL COMMENT '중분류 순번',
  `ITEM_SEQ` int(10) unsigned NOT NULL COMMENT '연구항목 순번',
  `TERM_REP_SEQ` int(10) unsigned NOT NULL COMMENT '동의어 대표어 순번',
  `CRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `CRT_ID` varchar(20) DEFAULT NULL COMMENT '생성자 ID',
  `UDT_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
  `UDT_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8 COMMENT='연구항목 동의어 관계정보';
