DELIMITER $$

DROP FUNCTION FN_GET_COMMON_CODE;

CREATE FUNCTION FN_GET_COMMON_CODE (P_COMM_GRP_ID VARCHAR(100),P_COMM_CD_ID VARCHAR(100),P_RETVAL VARCHAR(50))
RETURNS VARCHAR(100)
	BEGIN
		DECLARE COMM_VAL VARCHAR(100);
		SET COMM_VAL = '';
		
		SELECT	COMM_CD_NM
		INTO 	COMM_VAL
		FROM	CC_COMMON_CODE
		WHERE 	1=1
		AND 	COMM_GRP_ID = 'BMCDW_INSTCD'
		AND 	COMM_CD_ID = '032';

        RETURN COMM_VAL;
   end;
        
DELIMITER ;


--공통코드그룹
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_INSTCD','병원구분코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_PERIOD_CD','반복주기코드',NOW(),'0000000'	,NOW()	,'0000000');
--INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_CENSORING_CD','중도절단그룹코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_SHARE_CD','조건구분코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_METH_CD','연구방법구분코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_TAB_CD','연구항목구분코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_FORM_SEARCH_CD','서식지검색컬럼코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_LOG_CD','로그코드',NOW(),'0000000'	,NOW()	,'0000000');

INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_POPUP_LIST_CD','팝업목록코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_TXT_CD','텍스트코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_NUM_CD','숫자코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_INCLUDE_YN_CD','포함,제외코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_RANGE_CD','범위코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_AGG_CD','집계코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_DEVIATION_CD','편차코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_CC_CONT_CD','사례대조대조군배수코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_CC_MAT_CD','사례대조매치코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_REGEXP_LIKE_MODIFIER_CD','정규식 Modifier 코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_PERSONAL_DATA_TYPE_LIST_CD','개인자료업로드목록코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_CONDITION_CD','조건공유저장코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_PURPOSE_CD','추출목적코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_ITEM_TYPE_CD','항목유형코드',NOW(),'0000000'	,NOW()	,'0000000');
INSERT INTO CC_COMMON_CODE_GROUP(	COMM_GRP_ID	,COMM_GRP_NM	,CRT_DT	,CRT_ID	,UDT_DT	,UDT_ID)VALUES ('CDW_CODE_TYPE_CD','코드유형코드',NOW(),'0000000'	,NOW()	,'0000000');



--병원구분코드
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_INSTCD', '030', '전체',  1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_INSTCD', '031', '본원',  2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_INSTCD', '032', '칠곡',  3, 'Y', NOW(), '0000000', NOW(), '');

--반복주기코드
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_PERIOD_CD', 'RG_ENTRY_RGST_LST__ENT_DATE', '내원일자(외래)',  1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_PERIOD_CD', 'DG_DISS_LST__DISDT', '내원일자(입원)',  2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_PERIOD_CD', 'PI_ORDER_LST__DO_DATE', '진단-진단일자',  3, 'Y', NOW(), '0000000', NOW(), '');

--생존분석코드
/*
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_CENSORING_CD', '577', '사망여부',  1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_CENSORING_CD', '537', '수신자격여부',  2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_CENSORING_CD', '10000', '미내원',  3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_CENSORING_CD', '502', '수술/시술코드',  4, 'Y', NOW(), '0000000', NOW(), '');
*/


--조건구분코드(공유)
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_SHARE_CD', 'A', '전체공유조건', 1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_SHARE_CD', 'D', '과공유조건', 2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_SHARE_CD', 'S', '개인공유조건', 3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_SHARE_CD', 'P', '개인조건', 4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_SHARE_CD', 'E', '개인+데이터 조건', 5, 'Y', NOW(), '0000000', NOW(), '');




--연구방법구분코드
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_METH_CD', 'CS', '단면연구',  1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_METH_CD', 'CH', '코호트연구',  2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_METH_CD', 'CC', '사례대조연구',  3, 'Y', NOW(), '0000000', NOW(), '');

--연구항목구분코드
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'C', '조회조건',  1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'P', '주기',  2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'R', '연구항목',  3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'RQ', '중도절단',  4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'RE', '사건정의',  5, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'CA', '사례군',  6, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_TAB_CD', 'CO', '대조군',  7, 'Y', NOW(), '0000000', NOW(), '');

--서식지검색코드
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'PAT_SBST_NO', '환자대체번호',  'Y','','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'INSNM', '병원구분',  'Y','Y','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'DEPT_NAME', '소속부서명',  'Y','Y','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'ETPR_NAME', '소속작성자명',  'Y','Y','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'FORMNAME', '서식지명',  'Y','Y','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'RC_DATE', '작성일자',  'Y','DAT','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'CONTENTS', '서식기록내용',  'Y','Y','Y',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_FORM_SEARCH_CD', 'PAT_SBST_NO', '환자대체번호',  'Y','','',1, 'Y', NOW(), '0000000', NOW(), '');

--로그코드
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_LOG_CD', 'L', '로그인로그',  '','','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_LOG_CD', 'E', 'ETL로그',  '','','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_LOG_CD', 'P', '페이지접속로그',  '','','',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ, COMM_GRP_ID, COMM_CD_ID, COMM_CD_NM, COMM_CD_EXT1, COMM_CD_EXT2, COMM_CD_EXT3, SORT, USE_YN, CRT_DT, CRT_ID, UDT_DT, UDT_ID) VALUES (	0, 'CDW_LOG_CD', 'Q', '쿼리로그',  '','','',1, 'Y', NOW(), '0000000', NOW(), '');



/*팝업목록코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE','P_COMMON_CODE',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_KEY','P_COMMON_CODE_KEY',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_ORDR_CODE','P_ORDR_CODE',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_DISINX','P_DISINX',4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_1HT_MR','P_COMMON_CODE_1HT_MR',5, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_2HT_MR','P_COMMON_CODE_2HT_MR',6, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_3HT_MR','P_COMMON_CODE_3HT_MR',7, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_SYNONYM','P_SYNONYM',8, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_1H','P_COMMON_CODE_1H',9, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_2H','P_COMMON_CODE_2H',10, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_3H','P_COMMON_CODE_3H',11, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_1HT','P_COMMON_CODE_1HT',12, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_2HT','P_COMMON_CODE_2HT',13, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_POPUP_LIST_CD','P_COMMON_CODE_3HT','P_COMMON_CODE_3HT',14, 'Y', NOW(), '0000000', NOW(), '');

/*텍스트코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','BETWEEN','between',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','>','>',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','<','<',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','>=','>=',4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','<=','<=',5, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','EQ','=',6, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','LIKE','like',7, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','NOT_LIKE','not like',8, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','REGEXP_LIKE','REGEXP_LIKE',9, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_TXT_CD','REGEXP_NOT_LIKE','REGEXP_NOT_LIKE',10, 'Y', NOW(), '0000000', NOW(), '');

/*숫자형코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_NUM_CD','BETWEEN','between',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_NUM_CD','>','>',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_NUM_CD','<','<',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_NUM_CD','>=','>=',4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_NUM_CD','<=','<=',5, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_NUM_CD','EQ','=',6, 'Y', NOW(), '0000000', NOW(), '');

/*포함제외코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_INCLUDE_YN_CD','Y','포함',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_INCLUDE_YN_CD','N','제외',2, 'Y', NOW(), '0000000', NOW(), '');

/*범위코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_RANGE_CD','N','이전',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_RANGE_CD','R','범위',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_RANGE_CD','H','이후',3, 'Y', NOW(), '0000000', NOW(), '');

/*집계코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','MIN','MIN',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','MAX','MAX',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','AVG','AVG',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','FIRST','FIRST',4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','LAST','LAST',5, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','PER','주기',6, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','ALL','전체',7, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','PAST','이전',8, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_AGG_CD','SUM','합계',9, 'Y', NOW(), '0000000', NOW(), '');

/*편차코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_DEVIATION_CD','','선택',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_DEVIATION_CD','M','월',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_DEVIATION_CD','Y','년',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_DEVIATION_CD','Q','분기',4, 'Y', NOW(), '0000000', NOW(), '');

/*사례대조대조군배수코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_CONT_CD','1','1배',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_CONT_CD','2','2배',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_CONT_CD','3','3배',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_CONT_CD','4','4배',4, 'Y', NOW(), '0000000', NOW(), '');

/*사례대조매치코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_MAT_CD','N','미사용',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_MAT_CD','AM','Age Match',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_MAT_CD','SM','Sex Match',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CC_MAT_CD','ASM','Age Sex Match',4, 'Y', NOW(), '0000000', NOW(), '');

/*정규식 Modifier 코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_REGEXP_LIKE_MODIFIER_CD','i','대소문자구분 안함',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_REGEXP_LIKE_MODIFIER_CD','m','행시작,행끝 구분',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_REGEXP_LIKE_MODIFIER_CD','n','단일문자 정규식 연산자가 개행과 일치',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_REGEXP_LIKE_MODIFIER_CD','x','공백, 주석 무시',4, 'Y', NOW(), '0000000', NOW(), '');

/*개인자료업로드목록코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PERSONAL_DATA_TYPE_LIST_CD','PAT_SBST_NO','환자대체번호',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PERSONAL_DATA_TYPE_LIST_CD','PAT_NAID','주민번호(13자리)',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PERSONAL_DATA_TYPE_LIST_CD','PAT_ID','환자번호(7자리)',3, 'Y', NOW(), '0000000', NOW(), '');


/*조건공유저장코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CONDITION_CD','SC','환자조회',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CONDITION_CD','SI','연구조회',2, 'Y', NOW(), '0000000', NOW(), '');

/*추출목적코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PURPOSE_CD','SC','업무용',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PURPOSE_CD','SC','심사용',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PURPOSE_CD','SC','타기관전송용',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PURPOSE_CD','SC','연구용',4, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PURPOSE_CD','SC','통계용',5, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_PURPOSE_CD','SC','기타',6, 'Y', NOW(), '0000000', NOW(), '');

/*항목유형코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_ITEM_TYPE_CD','COD','코드',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_ITEM_TYPE_CD','TEX','텍스트',2, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_ITEM_TYPE_CD','NUM','숫자',3, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_ITEM_TYPE_CD','DAT','날짜',4, 'Y', NOW(), '0000000', NOW(), '');

/*코드유형코드*/
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CODE_TYPE_CD','JSN','JSON',1, 'Y', NOW(), '0000000', NOW(), '');
INSERT INTO CC_COMMON_CODE(COMM_GRP_SEQ,COMM_GRP_ID,COMM_CD_ID,COMM_CD_NM,SORT,USE_YN,CRT_DT,CRT_ID,UDT_DT,UDT_ID) VALUES (0,'CDW_CODE_TYPE_CD','SQL','SQL',2, 'Y', NOW(), '0000000', NOW(), '');

















