ALTER TABLE CC_ITEM_CONT ADD COLUMN DEPT_CODE VARCHAR(20);                      /* */
ALTER TABLE CC_ITEM_CONT ADD COLUMN CC_AGE_NUM INT(10) UNSIGNED;       /* 사례대조 나이편차 범위 컬럼 */
ALTER TABLE CC_ITEM_CONT_DATA ADD COLUMN TABLE_CNT INT(10) UNSIGNED;            /* 데이터저장 테이블 카운트 */
ALTER TABLE CC_ITEM_CONT_DATA_DETL ADD COLUMN ADD_ITEM_YN CHAR(1) DEFAULT 'N';             /* 추가아이템여부 */
ALTER TABLE CC_PERINX ADD COLUMN FIRST_FLAG CHAR(1) DEFAULT 'N';    /* 초기접속여부 N:초기접속, Y:2회이상접속 */

/*20170719 추가*/
ALTER TABLE CC_DISINX_LOV ADD COLUMN INSTCD CHAR(3);    /* 사업장코드 */
ALTER TABLE CC_ITEM_CATE_DETL ADD COLUMN INSTCD_YN CHAR(1);    /* 사업장적용여부 */

/*20170801 추가*/
ALTER TABLE CC_ITEM_MGMT ADD COLUMN ITEM_FIRST_YN CHAR(1) DEFAULT 'N';    /* 최초적용 유무 Y:최초적용 N:적용안함 */


/*20170927 추가 */
ALTER TABLE CC_COMMON_CODE_GROUP ADD COMM_GRP_ID varchar(50) NULL COMMENT '공통코드그룹ID' ;
ALTER TABLE CC_COMMON_CODE ADD COMM_GRP_ID varchar(50) NULL COMMENT '공통코드그룹ID' ;
ALTER TABLE CC_ITEM_CONT_DATA ADD TABLE_SIZE DECIMAL NULL COMMENT '사용자테이블크기' ;
ALTER TABLE CC_LOG_ACCESS ADD QUERY_LOG TEXT NULL COMMENT '쿼리로그메시지' ;

/*20171011 추가 */
ALTER TABLE CC_ITEM_CONT_DETL ADD ITEM_TEXT varchar(200) NULL COMMENT '항목텍스트' ;


/*20171030 추가 */
ALTER TABLE CC_ITEM_CONT_DETL ADD IS_NULL_OR_BLANK CHAR(1) NULL COMMENT 'NULL_OR_BLANK여부' ;
ALTER TABLE CC_ITEM_MGMT ADD SEARCH_CNT BIGINT UNSIGNED DEFAULT 0 NULL COMMENT '다빈도자동화_조회컬럼' ;



---------------------------------------------
drop & create
DROP bmcdw CC_BOARD_ATTACH;
CREATE TABLE `CC_BOARD_ATTACH` (
 `SEQ` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '일련번호',
 `DOCUMENT_SEQ` INT(10) UNSIGNED NOT NULL COMMENT '문서 일련번호',
 `BOARD_SEQ` INT(10) UNSIGNED NOT NULL COMMENT '게시판 SEQ',
 `ATTACH_PATH` VARCHAR(512) NOT NULL COMMENT '첨부파일 경로',
 `ATTACH_SIZE` INT(10) UNSIGNED NOT NULL COMMENT '첨부파일 크기',
 `ORDER` INT(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT '순서',
 `UDT_DT` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '수정일자',
 `UDT_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '변경자 ID',
 `CRT_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '생성자 ID',
 `CRT_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
 `SAVE_FILE_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '실제 저장되는 파일명',
 `FILE_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '원래 파일명',
 PRIMARY KEY (`SEQ`),
 INDEX `FK_CC_BOARD_ATTACH_CC_BOARD` (`DOCUMENT_SEQ`),
 CONSTRAINT `FK_CC_BOARD_ATTACH_CC_BOARD` FOREIGN KEY (`DOCUMENT_SEQ`) REFERENCES `CC_BOARD` (`SEQ`) ON DELETE CASCADE
)
COMMENT='게시판 첨부파일 관리'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=42
;


DROP bmcdw CC_ETLLOG_ACCESS;
